name: aptible

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Deploy to Aptible
      uses: aptible/aptible-deploy-action@v4
      with:
        type: git
        app: deploy-demo-app
        environment: savii-staging
        username: ${{ secrets.APTIBLE_USERNAME }}
        password: ${{ secrets.APTIBLE_PASSWORD }}
